/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package threads;

public class App {


    public static void main(String[] args) {
        Thread t1 = new Thread(new MyThread(), "Thread 1");
        Thread t2 = new Thread(new MyThread(), "Thread 2");
        Thread t3 = new Thread(new MyThread(), "Thread 3");
        t1.start();
        t2.start();
        t3.start();

        Thread t4 = new Thread(new MyThread(), "Thread 4");

        try {
            t3.join();
        } catch (Exception e) {
            // TODO: handle exception
        }
        t4.start();
    }
}

class MyThread implements Runnable{
    @Override
    public void run() {
        System.out.println("Active Threads:" + Thread.activeCount());

        System.out.println("Start Thread:" + Thread.currentThread().getName());

        try {
            Thread.sleep(3000);
        } catch (Exception e) {
            // TODO: handle exception
        }

        System.out.println("End  thread:" + Thread.currentThread().getName());

    }
}